name: Deploy

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Deploy
        run: |
          echo "Deploying..."
          echo "Artifact is available at ${{ inputs.artifact }}"
